# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "Oregon Chinese Coalition"
title_separator          : "-"
name                     : "Oregon Chinese Coalition"
description              : "The main hub for everything you need to know about Portland's Chinese Community."
url                      : "https://pdxchinese.org" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "PDXChinese/pdxchinese.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "https://res.cloudinary.com/dhngj18do/image/upload/f_auto,q_auto/v1/images/500x300"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 120
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "ChineseOregon"
facebook:
  username               : "Oregon-Chinese-Coalition-568850810154157"
  app_id                 :
  publisher              :
youtube:
  channel                : "UCEirGv1g7DAC0udxm_-Fvxg"
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
instagram:
  username               : "oregonchinesecoalition"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             :
  avatar           : # path of avatar image, e.g. "https://res.cloudinary.com/dhngj18do/image/upload/f_auto,q_auto/v1/images/bio-photo"
  bio              :
  location         :
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  about_history:
    output: true
    permalink: /about/history/:path/
  chinatown_gallery:
    output: true
    permalink: /chinatown/:path/
  chinatown_engage:
    output: true
    permalink: /chinatown/engage/:path/
  chinatown_wonglaundry:
    output: true
    permalink: /chinatown/wonglaundry/:path/
  chinatown_newyear:
    output: true
    permalink: /chinatown/newyear/:path/
  communities_media:
    output: true
    permalink: /resources/:collection/:path/
  communities_culture:
    output: true
    permalink: /resources/:collection/:path/
  communities_mandarin:
    output: true
    permalink: /resources/:collection/:path/
  communities_religious:
    output: true
    permalink: /resources/:collection/:path/
  communities_business:
    output: true
    permalink: /resources/:collection/:path/
  disaster_conexbox:
    output: true
    permalink: /resources/:collection/:path/
  disaster_resilience:
    output: true
    permalink: /resources/:collection/:path/
  benefits_community:
    output: true
    permalink: /resources/:collection/:path/
  benefits_resources:
    output: true
    permalink: /resources/:collection/:path/
  activities_academies:
    output: true
    permalink: /resources/:collection/:path/
  activities_afterschool:
    output: true
    permalink: /resources/:collection/:path/
  activities_clubs:
    output: true
    permalink: /resources/:collection/:path/
  activities_healthy:
    output: true
    permalink: /resources/:collection/:path/
  activities_artinstitute:
    output: true
    permalink: /resources/:collection/:path/
  activities_sports:
    output: true
    permalink: /resources/:collection/:path/
  professionals_accountant:
    output: true
    permalink: /resources/:collection/:path/
  professionals_acupuncture:
    output: true
    permalink: /resources/:collection/:path/
  professionals_architect:
    output: true
    permalink: /resources/:collection/:path/
  professionals_artist:
    output: true
    permalink: /resources/:collection/:path/
  professionals_attorney:
    output: true
    permalink: /resources/:collection/:path/
  professionals_collegecounselor:
    output: true
    permalink: /resources/:collection/:path/
  professionals_computerprogramming:
    output: true
    permalink: /resources/:collection/:path/
  professionals_cti:
    output: true
    permalink: /resources/:collection/:path/
  professionals_dentistorthodontist:
    output: true
    permalink: /resources/:collection/:path/
  professionals_engineer:
    output: true
    permalink: /resources/:collection/:path/
  professionals_financialadvisor:
    output: true
    permalink: /resources/:collection/:path/
  professionals_importexport:
    output: true
    permalink: /resources/:collection/:path/
  professionals_interpretation:
    output: true
    permalink: /resources/:collection/:path/
  professionals_mortgagebroker:
    output: true
    permalink: /resources/:collection/:path/
  professionals_moving:
    output: true
    permalink: /resources/:collection/:path/
  professionals_paralegal:
    output: true
    permalink: /resources/:collection/:path/
  professionals_physicaltherapist:
    output: true
    permalink: /resources/:collection/:path/
  professionals_physician:
    output: true
    permalink: /resources/:collection/:path/
  professionals_realestatebroker:
    output: true
    permalink: /resources/:collection/:path/
  professionals_shippingchina:
    output: true
    permalink: /resources/:collection/:path/
  professionals_socialworker:
    output: true
    permalink: /resources/:collection/:path/
  professionals_taxreturn:
    output: true
    permalink: /resources/:collection/:path/
  professionals_tradeshow:
    output: true
    permalink: /resources/:collection/:path/
  professionals_travelagent:
    output: true
    permalink: /resources/:collection/:path/
  professionals_tutor:
    output: true
    permalink: /resources/:collection/:path/
  youthconf:
    output: true
    permalink: /youthconference/:path/
  pvsafiles:
    output: true
    permalink: /pvsafiles/:path/
  artcontestfiles:
    output: true
    permalink: /artcontestfiles/:path/
  festival:
    output: true
    permalink: /chinesefestival/:path/
  peeradvisors:
    output: true
    permalink: /peeradvisors/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # chinatown_gallery
  - scope:
      path: ""
      type: about_history
    values:
      layout: single
      author_profile: false
  # chinatown_gallery
  - scope:
      path: ""
      type: chinatown_gallery
    values:
      layout: single
      author_profile: false
  # chinatown_engage
  - scope:
      path: ""
      type: chinatown_engage
    values:
      layout: single
      author_profile: false
  # chinatown_wonglaundry
  - scope:
      path: ""
      type: chinatown_wonglaundry
    values:
      layout: single
      author_profile: false
  # chinatown_newyear
  - scope:
      path: ""
      type: chinatown_newyear
    values:
      layout: single
      author_profile: false
  # communities_media
  - scope:
      path: ""
      type: communities_media
    values:
      layout: single
      author_profile: false
  # communities_culture
  - scope:
      path: ""
      type: communities_culture
    values:
      layout: single
      author_profile: false
  # communities_mandarin
  - scope:
      path: ""
      type: communities_mandarin
    values:
      layout: single
      author_profile: false
  # communities_religious
  - scope:
      path: ""
      type: communities_religious
    values:
      layout: single
      author_profile: false
  # communities_business
  - scope:
      path: ""
      type: communities_business
    values:
      layout: single
      author_profile: false
  # disaster_conexbox
  - scope:
      path: ""
      type: disaster_conexbox
    values:
      layout: single
      author_profile: false
  # disaster_resilience
  - scope:
      path: ""
      type: disaster_resilience
    values:
      layout: single
      author_profile: false
  # benefits_community
  - scope:
      path: ""
      type: benefits_community
    values:
      layout: single
      author_profile: false
  # benefits_resources
  - scope:
      path: ""
      type: benefits_resources
    values:
      layout: single
      author_profile: false
  # activities_academies
  - scope:
      path: ""
      type: activities_academies
    values:
      layout: single
      author_profile: false
  # activities_afterschool
  - scope:
      path: ""
      type: activities_afterschool
    values:
      layout: single
      author_profile: false
  # activities_healthy
  - scope:
      path: ""
      type: activities_healthy
    values:
      layout: single
      author_profile: false
  # activities_artinstitute
  - scope:
      path: ""
      type: activities_artinstitute
    values:
      layout: single
      author_profile: false
  # activities_sports
  - scope:
      path: ""
      type: activities_sports
    values:
      layout: single
      author_profile: false
  # professionals_accountant
  - scope:
      path: ""
      type: professionals_accountant
    values:
      layout: single
      author_profile: false
  # professionals_acupuncture
  - scope:
      path: ""
      type: professionals_acupuncture
    values:
      layout: single
      author_profile: false
  # professionals_architect
  - scope:
      path: ""
      type: professionals_architect
    values:
      layout: single
      author_profile: false
  # professionals_artist
  - scope:
      path: ""
      type: professionals_artist
    values:
      layout: single
      author_profile: false
  # professionals_attorney
  - scope:
      path: ""
      type: professionals_attorney
    values:
      layout: single
      author_profile: false
  # professionals_collegecounselor
  - scope:
      path: ""
      type: professionals_collegecounselor
    values:
      layout: single
      author_profile: false
  # professionals_computerprogramming
  - scope:
      path: ""
      type: professionals_computerprogramming
    values:
      layout: single
      author_profile: false
  # professionals_cti
  - scope:
      path: ""
      type: professionals_cti
    values:
      layout: single
      author_profile: false
  # professionals_dentistorthodontist
  - scope:
      path: ""
      type: professionals_dentistorthodontist
    values:
      layout: single
      author_profile: false
  # professionals_engineer
  - scope:
      path: ""
      type: professionals_engineer
    values:
      layout: single
      author_profile: false
  # professionals_financialadvisor
  - scope:
      path: ""
      type: professionals_financialadvisor
    values:
      layout: single
      author_profile: false
  # professionals_importexport
  - scope:
      path: ""
      type: professionals_importexport
    values:
      layout: single
      author_profile: false
  # professionals_interpretation
  - scope:
      path: ""
      type: professionals_interpretation
    values:
      layout: single
      author_profile: false
  # professionals_mortgagebroker
  - scope:
      path: ""
      type: professionals_mortgagebroker
    values:
      layout: single
      author_profile: false
  # professionals_moving
  - scope:
      path: ""
      type: professionals_moving
    values:
      layout: single
      author_profile: false
  # professionals_paralegal
  - scope:
      path: ""
      type: professionals_paralegal
    values:
      layout: single
      author_profile: false
  # professionals_physicaltherapist
  - scope:
      path: ""
      type: professionals_physicaltherapist
    values:
      layout: single
      author_profile: false
  # professionals_physician
  - scope:
      path: ""
      type: professionals_physician
    values:
      layout: single
      author_profile: false
  # professionals_realestatebroker
  - scope:
      path: ""
      type: professionals_realestatebroker
    values:
      layout: single
      author_profile: false
  # professionals_shippingchina
  - scope:
      path: ""
      type: professionals_shippingchina
    values:
      layout: single
      author_profile: false
  # professionals_socialworker
  - scope:
      path: ""
      type: professionals_socialworker
    values:
      layout: single
      author_profile: false
  # professionals_taxreturn
  - scope:
      path: ""
      type: professionals_taxreturn
    values:
      layout: single
      author_profile: false
  # professionals_tradeshow
  - scope:
      path: ""
      type: professionals_tradeshow
    values:
      layout: single
      author_profile: false
  # professionals_travelagent
  - scope:
      path: ""
      type: professionals_travelagent
    values:
      layout: single
      author_profile: false
  # professionals_tutor
  - scope:
      path: ""
      type: professionals_tutor
    values:
      layout: single
      author_profile: false
  # youthconf
  - scope:
      path: ""
      type: youthconf
    values:
      layout: single
      author_profile: false
  # pvsafiles
  - scope:
      path: ""
      type: pvsafiles
    values:
      layout: single
      author_profile: false
  # artcontestfiles
  - scope:
      path: ""
      type: artcontestfiles
    values:
      layout: single
      author_profile: false
  # festival
  - scope:
      path: ""
      type: festival
    values:
      layout: single
      author_profile: false
  # peeradvisors
  - scope:
      path: ""
      type: peeradvisors
    values:
      layout: single
      author_profile: false
